### ISSUE TITLE
Treble Setting presets

### ISSUE THREAD

**Issue by phhusson** [tabletseeker/treble_build_aosp#3]
https://github.com/tabletseeker/treble_build_aosp/blob/721ab2e593e1e9e8010b298636fd75fe426d627f/README.md?plain=1#L35

Hello,

Thanks for your project.

With regards to the presets, did you actually test your XML changes? To the best of my knowledge this doesn't work.
Also, before setting your custom settings inside the ROM, if the settings are global for the device, it is preferred to share those presets to everyone through https://github.com/phhusson/treble_presets . With this, everyone automatically gets the community-developed settings made for their devices over-the-air on the first boot.

**Comment by tabletseeker** [comment]
Hey man, yes I've built quite a few r14 images with the modified phh xmls and the settings are applied on the first boot.

To be more specific, the effects are either visible immediately or within 30 seconds of the first boot, but  the actual phh settings sliders indicating the changes, can take up to a couple minutes or a reboot to correctly display them.

These are just my personally preferred settings, the idea being that everyone should tweak them to fit their needs, but sure I'll have a look that.

I should probably update the readme to explain in detail what each settings value does, though.
