### ISSUE TITLE
buildscript fails

### ISSUE THREAD

**Issue by khaberz** [tabletseeker/treble_build_aosp#4]
Buildscript fails, attaching log as per xda-forum request. Please let me know if I can provide more info.
[log.txt](https://github.com/tabletseeker/treble_build_aosp/files/14170768/log.txt)

**Comment by tabletseeker** [comment]
Hi there.

Please run `bash -x treble_build_aosp/build.sh` and copy/paste the terminal output in here. You can select it by pressing Ctrl.

If you're using Debian 10 Buster, some of the packages automatically installed by the env function won't be available, thus causing an error.  I'm not sure if it's even possible to complete the build on Buster, but Bookworm is recommended.
The package openjdk-17-jdk is the main reason.

Apt is also returning a mirror error btw.
```
Err:1 http://mirrors.linode.com/debian stable InRelease
```

**Comment by khaberz** [comment]
Hi,

I am running bookworm. Here you go:

`+ echo '--> Applying TrebleDroid patches'
--> Applying TrebleDroid patches
+ bash /home/khaberz/aosp/treble_build_aosp/apply-patches.sh /home/khaberz/aosp/treble_build_aosp trebledroid
+ echo

+ echo '--> Applying personal patches'
--> Applying personal patches
+ bash /home/khaberz/aosp/treble_build_aosp/apply-patches.sh /home/khaberz/aosp/treble_build_aosp personal
+ echo

+ echo '--> Generating makefiles'
--> Generating makefiles
+ cd device/phh/treble
treble_build_aosp/build.sh: line 283: cd: device/phh/treble: No such file or directory
+ cp /home/khaberz/aosp/treble_build_aosp/aosp.mk .
+ bash generate.sh aosp
bash: generate.sh: No such file or directory
+ cd ../../..
+ echo

+ setupEnv
+ echo '--> Setting up build environment'
--> Setting up build environment
+ source build/envsetup.sh
+ mkdir -p /home/khaberz/builds
+ echo

+ buildTrebleApp






































































+ settings='\tconfig_navBarInteractionMode:2:
                config_audio_notif_vol_default:0:
                config_defaultHapticFeedbackIntensity:0:
                config_audio_ring_vol_default:0:
                def_haptic_feedback:false:
                def_bluetooth_on:false:
                def_sound_effects_enabled:false:
                def_notifications_use_ring_volume:false'
+ for i in "${xml[@]}"
+ index=1
+ '[' 1 -ne 0 ']'
++ echo -e '\tconfig_navBarInteractionMode:2:
                config_audio_notif_vol_default:0:
                config_defaultHapticFeedbackIntensity:0:
                config_audio_ring_vol_default:0:
                def_haptic_feedback:false:
                def_bluetooth_on:false:
                def_sound_effects_enabled:false:
                def_notifications_use_ring_volume:false'
++ sed -e '/config_/ s|\t*|//frameworks/base/core/res/res/values/config.xml:|'
+ settings='//frameworks/base/core/res/res/values/config.xml:config_navBarInteractionMode:2:
//frameworks/base/core/res/res/values/config.xml:config_audio_notif_vol_default:0:
//frameworks/base/core/res/res/values/config.xml:config_defaultHapticFeedbackIntensity:0:
//frameworks/base/core/res/res/values/config.xml:config_audio_ring_vol_default:0:
                def_haptic_feedback:false:
                def_bluetooth_on:false:
                def_sound_effects_enabled:false:
                def_notifications_use_ring_volume:false'
+ for i in "${xml[@]}"
+ index=2
+ '[' 0 -ne 0 ']'
+ for i in "${xml[@]}"
+ index=3
+ '[' 1 -ne 0 ']'
++ echo -e '//frameworks/base/core/res/res/values/config.xml:config_navBarInteractionMode:2:
//frameworks/base/core/res/res/values/config.xml:config_audio_notif_vol_default:0:
//frameworks/base/core/res/res/values/config.xml:config_defaultHapticFeedbackIntensity:0:
//frameworks/base/core/res/res/values/config.xml:config_audio_ring_vol_default:0:
                def_haptic_feedback:false:
                def_bluetooth_on:false:
                def_sound_effects_enabled:false:
                def_notifications_use_ring_volume:false'
++ sed -e '/def_/ s|\t*|//frameworks/base/packages/SettingsProvider/res/values/defaults.xml:|'
+ settings='//frameworks/base/core/res/res/values/config.xml:config_navBarInteractionMode:2:
//frameworks/base/core/res/res/values/config.xml:config_audio_notif_vol_default:0:
//frameworks/base/core/res/res/values/config.xml:config_defaultHapticFeedbackIntensity:0:
//frameworks/base/core/res/res/values/config.xml:config_audio_ring_vol_default:0:
//frameworks/base/packages/SettingsProvider/res/values/defaults.xml:def_haptic_feedback:false:
//frameworks/base/packages/SettingsProvider/res/values/defaults.xml:def_bluetooth_on:false:
//frameworks/base/packages/SettingsProvider/res/values/defaults.xml:def_sound_effects_enabled:false:
//frameworks/base/packages/SettingsProvider/res/values/defaults.xml:def_notifications_use_ring_volume:false'
+ for i in "${xml[@]}"
+ index=4
+ '[' 0 -ne 0 ']'
+ IFS=:
+ '[' 0 -gt 0 ']'
+ read -ra array
++ echo '//frameworks/base/core/res/res/values/config.xml:config_navBarInteractionMode:2:
//frameworks/base/core/res/res/values/config.xml:config_audio_notif_vol_default:0:
//frameworks/base/core/res/res/values/config.xml:config_defaultHapticFeedbackIntensity:0:
//frameworks/base/core/res/res/values/config.xml:config_audio_ring_vol_default:0:
//frameworks/base/packages/SettingsProvider/res/values/defaults.xml:def_haptic_feedback:false:
//frameworks/base/packages/SettingsProvider/res/values/defaults.xml:def_bluetooth_on:false:
//frameworks/base/packages/SettingsProvider/res/values/defaults.xml:def_sound_effects_enabled:false:
//frameworks/base/packages/SettingsProvider/res/values/defaults.xml:def_notifications_use_ring_volume:false'
++ tr -d '\n'
+ (( x=0 ))
++ echo 24/3
++ bc
+ (( x<8 ))
+ '[' 0 -eq 0 ']'
+ dest=//frameworks/base/core/res/res/values/config.xml
+ grep=config_navBarInteractionMode
+ replace=2
++ grep -n config_navBarInteractionMode //frameworks/base/core/res/res/values/config.xml
grep: ++ cut -d : -f1
//frameworks/base/core/res/res/values/config.xml: No such file or directory
+ line_nr=
+ '[' '!' -z '' ']'
+ echo -e '\n grep failed on config_patch: config_navBarInteractionMode'

 grep failed on config_patch: config_navBarInteractionMode
+ (( x++ ))
++ echo 24/3
++ bc
+ (( x<8 ))
+ '[' 1 -eq 0 ']'
+ dest=//frameworks/base/core/res/res/values/config.xml
+ grep=config_audio_notif_vol_default
+ replace=0
++ grep -n config_audio_notif_vol_default //frameworks/base/core/res/res/values/config.xml
++ cut -d : -f1
grep: //frameworks/base/core/res/res/values/config.xml: No such file or directory
+ line_nr=
+ '[' '!' -z '' ']'
+ echo -e '\n grep failed on config_patch: config_audio_notif_vol_default'

 grep failed on config_patch: config_audio_notif_vol_default
+ (( x++ ))
++ echo 24/3
++ bc
+ (( x<8 ))
+ '[' 2 -eq 0 ']'
+ dest=//frameworks/base/core/res/res/values/config.xml
+ grep=config_defaultHapticFeedbackIntensity
+ replace=0
++ grep -n config_defaultHapticFeedbackIntensity //frameworks/base/core/res/res/values/config.xml
grep: ++ cut -d : -f1
//frameworks/base/core/res/res/values/config.xml: No such file or directory
+ line_nr=
+ '[' '!' -z '' ']'
+ echo -e '\n grep failed on config_patch: config_defaultHapticFeedbackIntensity'

 grep failed on config_patch: config_defaultHapticFeedbackIntensity
+ (( x++ ))
++ echo 24/3
++ bc
+ (( x<8 ))
+ '[' 3 -eq 0 ']'
+ dest=//frameworks/base/core/res/res/values/config.xml
+ grep=config_audio_ring_vol_default
+ replace=0
++ grep -n config_audio_ring_vol_default //frameworks/base/core/res/res/values/config.xml
++ cut -d : -f1
grep: //frameworks/base/core/res/res/values/config.xml: No such file or directory
+ line_nr=
+ '[' '!' -z '' ']'
+ echo -e '\n grep failed on config_patch: config_audio_ring_vol_default'

 grep failed on config_patch: config_audio_ring_vol_default
+ (( x++ ))
++ echo 24/3
++ bc
+ (( x<8 ))
+ '[' 4 -eq 0 ']'
+ dest=//frameworks/base/packages/SettingsProvider/res/values/defaults.xml
+ grep=def_haptic_feedback
+ replace=false
++ grep -n def_haptic_feedback //frameworks/base/packages/SettingsProvider/res/values/defaults.xml
grep: ++ cut -d : -f1
//frameworks/base/packages/SettingsProvider/res/values/defaults.xml: No such file or directory
+ line_nr=
+ '[' '!' -z '' ']'
+ echo -e '\n grep failed on config_patch: def_haptic_feedback'

 grep failed on config_patch: def_haptic_feedback
+ (( x++ ))
++ echo 24/3
++ bc
+ (( x<8 ))
+ '[' 5 -eq 0 ']'
+ dest=//frameworks/base/packages/SettingsProvider/res/values/defaults.xml
+ grep=def_bluetooth_on
+ replace=false
++ grep -n def_bluetooth_on //frameworks/base/packages/SettingsProvider/res/values/defaults.xml
grep: ++ cut -d : -f1
//frameworks/base/packages/SettingsProvider/res/values/defaults.xml: No such file or directory
+ line_nr=
+ '[' '!' -z '' ']'
+ echo -e '\n grep failed on config_patch: def_bluetooth_on'

 grep failed on config_patch: def_bluetooth_on
+ (( x++ ))
++ echo 24/3
++ bc
+ (( x<8 ))
+ '[' 6 -eq 0 ']'
+ dest=//frameworks/base/packages/SettingsProvider/res/values/defaults.xml
+ grep=def_sound_effects_enabled
+ replace=false
++ cut -d : -f1
++ grep -n def_sound_effects_enabled //frameworks/base/packages/SettingsProvider/res/values/defaults.xml
grep: //frameworks/base/packages/SettingsProvider/res/values/defaults.xml: No such file or directory
+ line_nr=
+ '[' '!' -z '' ']'
+ echo -e '\n grep failed on config_patch: def_sound_effects_enabled'

 grep failed on config_patch: def_sound_effects_enabled
+ (( x++ ))
++ echo 24/3
++ bc
+ (( x<8 ))
+ '[' 7 -eq 0 ']'
+ dest=//frameworks/base/packages/SettingsProvider/res/values/defaults.xml
+ grep=def_notifications_use_ring_volume
+ replace=false
++ grep -n def_notifications_use_ring_volume //frameworks/base/packages/SettingsProvider/res/values/defaults.xml
grep: ++ cut -d : -f1
//frameworks/base/packages/SettingsProvider/res/values/defaults.xml: No such file or directory
+ line_nr=
+ '[' '!' -z '' ']'
+ echo -e '\n grep failed on config_patch: def_notifications_use_ring_volume'

 grep failed on config_patch: def_notifications_use_ring_volume
+ (( x++ ))
++ echo 24/3
++ bc
+ (( x<8 ))
++ printf '%*s%s' 4
+ space='    '
+ init_core='    <bool name="config_defaultBatteryPercentageSetting">true</bool>'
++ grep -n config_defaultBatteryPercentageSetting //frameworks/base/core/res/res/values/config.xml
grep: ++ cut -d : -f1
//frameworks/base/core/res/res/values/config.xml: No such file or directory
+ grep_check=
+ '[' -z '' ']'
++ grep -n config_battery_percentage_setting_available //frameworks/base/core/res/res/values/config.xml
++ cut -d : -f1
grep: //frameworks/base/core/res/res/values/config.xml: No such file or directory
+ init_line=
+ (( init_line++ ))
++ sed -n ' p' //frameworks/base/core/res/res/values/config.xml
sed: can't read //frameworks/base/core/res/res/values/config.xml: No such file or directory
++ grep -Eo 'true|false'
+ '[' = false ']'
treble_build_aosp/build.sh: line 413: [: =: unary operator expected
+ makeKeys
+ [[ 1 6 == *\6* ]]
+ /home/khaberz/aosp/treble_build_aosp/misc/keymaker.sh
treble_build_aosp/build.sh: line 491: /home/khaberz/aosp/treble_build_aosp/misc/keymaker.sh: Permission denied
+ buildVanillaVariant
+ echo '--> Building treble_arm64_bvN'
--> Building treble_arm64_bvN
+ lunch treble_arm64_bvN-userdebug
treble_build_aosp/build.sh: line 515: lunch: command not found
++ nproc --all
+ make -j1 installclean
make: *** No rule to make target 'installclean'.  Stop.
++ nproc --all
+ make -j1 systemimage
make: *** No rule to make target 'systemimage'.  Stop.
+ mv /system.img /home/khaberz/builds/system-treble_arm64_bvN.img
mv: cannot stat '/system.img': No such file or directory
+ echo

+ buildGappsVariant
+ echo '--> Building treble_arm64_bgN'
--> Building treble_arm64_bgN
+ lunch treble_arm64_bgN-userdebug
treble_build_aosp/build.sh: line 524: lunch: command not found
++ nproc --all
+ make -j1 installclean
make: *** No rule to make target 'installclean'.  Stop.
++ nproc --all
+ make -j1 systemimage
make: *** No rule to make target 'systemimage'.  Stop.
+ mv /system.img /home/khaberz/builds/system-treble_arm64_bgN.img
mv: cannot stat '/system.img': No such file or directory
+ echo

+ buildVndkliteVariants
+ echo '--> Building treble_arm64_bvN-vndklite'
--> Building treble_arm64_bvN-vndklite
+ cd treble_adapter
treble_build_aosp/build.sh: line 533: cd: treble_adapter: No such file or directory
+ sudo bash lite-adapter.sh 64 /home/khaberz/builds/system-treble_arm64_bvN.img
bash: lite-adapter.sh: No such file or directory
+ mv s.img /home/khaberz/builds/system-treble_arm64_bvN-vndklite.img
mv: cannot stat 's.img': No such file or directory
+ sudo rm -rf d tmp
+ echo '--> Building treble_arm64_bgN-vndklite'
--> Building treble_arm64_bgN-vndklite
+ sudo bash lite-adapter.sh 64 /home/khaberz/builds/system-treble_arm64_bgN.img
bash: lite-adapter.sh: No such file or directory
+ mv s.img /home/khaberz/builds/system-treble_arm64_bgN-vndklite.img
mv: cannot stat 's.img': No such file or directory
+ sudo rm -rf d tmp
+ cd ..
+ echo

+ generatePackages
+ echo '--> Generating packages'
--> Generating packages
++ date +%Y%m%d
+ buildDate=20240206
+ xz -cv /home/khaberz/builds/system-treble_arm64_bvN.img -T0
/home/khaberz/builds/system-treble_arm64_bvN.img (1/1)
xz: /home/khaberz/builds/system-treble_arm64_bvN.img: No such file or directory
+ xz -cv /home/khaberz/builds/system-treble_arm64_bvN-vndklite.img -T0
/home/khaberz/builds/system-treble_arm64_bvN-vndklite.img (1/1)
xz: /home/khaberz/builds/system-treble_arm64_bvN-vndklite.img: No such file or directory
+ xz -cv /home/khaberz/builds/system-treble_arm64_bgN.img -T0
/home/khaberz/builds/system-treble_arm64_bgN.img (1/1)
xz: /home/khaberz/builds/system-treble_arm64_bgN.img: No such file or directory
+ xz -cv /home/khaberz/builds/system-treble_arm64_bgN-vndklite.img -T0
/home/khaberz/builds/system-treble_arm64_bgN-vndklite.img (1/1)
xz: /home/khaberz/builds/system-treble_arm64_bgN-vndklite.img: No such file or directory
+ rm -rf '/home/khaberz/builds/system-*.img'
+ echo

+ generateOta
treble_build_aosp/build.sh: line 572: generateOta: command not found
++ date +%s
+ END=1707200365
+ ELAPSEDM=0
+ ELAPSEDS=2
+ echo '--> Buildbot completed in 0 minutes and 2 seconds'
--> Buildbot completed in 0 minutes and 2 seconds
+ echo

[khaberz@usnode aosp]$ `

**Comment by tabletseeker** [comment]
> I am running bookworm

You have Buster sources in your /etc/apt/sources.list and some mirrors are dead.
```
Hit:2 http://mirrors.linode.com/debian stable-updates InRelease
Err:1 http://mirrors.linode.com/debian stable InRelease
  Couldn't create temporary file /tmp/apt.conf.pLcbDF for passing config to apt-key
Err:2 http://mirrors.linode.com/debian stable-updates InRelease
  Couldn't create temporary file /tmp/apt.conf.8N6Rad for passing config to apt-key
Hit:3 http://apt-longview.linode.com buster InRelease
Err:3 http://apt-longview.linode.com buster InRelease
  Couldn't create temporary file /tmp/apt.conf.ovwz2V for passing config to apt-key
```
This could be due to an upgrade, but make sure you have proper Bookworm sources.
```
deb http://deb.debian.org/debian bookworm main non-free-firmware
deb-src http://deb.debian.org/debian bookworm main non-free-firmware

deb http://deb.debian.org/debian-security/ bookworm-security main non-free-firmware
deb-src http://deb.debian.org/debian-security/ bookworm-security main non-free-firmware

deb http://deb.debian.org/debian bookworm-updates main non-free-firmware
deb-src http://deb.debian.org/debian bookworm-updates main non-free-firmware
```
In your terminal settings, set scrollback to unlimited. Then after running `bash -x treble_build_aosp/build.sh`,  using the scroll bar go all the way to the top, select the first line, press and hold Shift, scroll to the bottom and select the end. That should get the entire output. (Please use a code tag for the output)

I need the full output to be sure, but it looks like a path issue.

**Comment by khaberz** [comment]
Fixed my apt-sources, thanks. No further updates after that.

The above is my full log. When I call the script, the GUI comes up, I make no changes and after OK, the above is the full output I can see - scrolling up all the way to where I can still see the GUI.

**Comment by tabletseeker** [comment]
The first line would say `bash -x treble_build_aosp/build.sh` if it were the full output. Make sure you set your terminal to unlimited scrolling so everything is displayed.

What I need to know is this bit, which occurs at the beginning of the script:
```
BL=$PWD/treble_build_aosp
BD=$HOME/builds
```
Your $PWD variable is empty and initRepos function is not called.
This only happens when the upper dir already has a .repo folder. `[ ! -d .repo ]`

My guess is that you didn't do `mkdir aosp; cd aosp` before cloning, but please try to provide the full output first.

**Comment by khaberz** [comment]
Again, as I mentioned above, the top is the GUI. 

Also, I did `mkdir aosp; cd aosp`

Also:
`
[khaberz@usnode aosp]$ echo "$PWD"
/home/khaberz/aosp
`

Here's a screenshot of the terminal as I see it: 
![Screenshot 2024-02-06 094245](https://github.com/tabletseeker/treble_build_aosp/assets/41310714/bd7e9168-d1bf-4ae8-81c9-630905faf95e)

**Comment by tabletseeker** [comment]
Synching or initializing with repo isn't working correctly on your machine or not installed at all. This could be due to missing sources, because the repo package is only available under contrib. (Updating Readme)
Add the following to /etc/apt/sources.list and run `sudo apt-get update` afterwards.
```
deb https://deb.debian.org/debian/ bookworm main contrib non-free-firmware
deb-src https://deb.debian.org/debian/ bookworm main contrib non-free-firmware
```
> Also: [khaberz@usnode aosp]$ echo "$PWD" /home/khaberz/aosp

No I mean inside the shell that you're executing the script in, $PWD is empty.
```
settings='//frameworks/base/core/res/res/values/config.xml:config_navBarInteractionMode:2:
//frameworks/base/core/res/res/values/config.xml:config_audio_notif_vol_default:0:
//frameworks/base/core/res/res/values/config.xml:config_defaultHapticFeedbackIntensity:0:
//frameworks/base/core/res/res/values/config.xml:config_audio_ring_vol_default:0:
```
The full path should be included, representing $PWD like so
`$PWD/frameworks/base/core/res/res/values/config.xml:config_audio_notif_vol_default:0`, but in your case it's empty.

$PWD can sometimes be empty in virtual environments when ~/ is involved.

Delete the whole aosp folder and clone again.

I ran it myself now on a debian install. Here is what the beginning of the output should look like:
```
user@debian:~/aosp$ bash -x treble_build_aosp/build.sh
+ echo
--------------------------------------
+ echo '          AOSP 14.0 Buildbot          '
          AOSP 14.0 Buildbot          
+ echo '                  by                  '
                  by                  
+ echo '             tablet_seeker            '
             tablet_seeker            
+ echo --------------------------------------
+ BL=/home/user/aosp/treble_build_aosp
+ BD=/home/user/builds
++ date +%s
+ START=1707224644
+ buildList
+ true
+ exec
```

**Comment by khaberz** [comment]
OK, tried that and now my disk ran out of space (it's a VPS with small disk allocation). I'll see what I can do about that and try build another box to try that on. Until then, you can close this one, sorry about that.

PS: If you ever create a build with all the right modifications for a Wifi Tab S6, I am happy to test :-)

**Comment by tabletseeker** [comment]
Sure, no problem. The build server will be probably be able to start taking requests by the end of this month. You'll be able to submit a build request with all your preferred settings and mods.

I would still be interested if you solved the $PWD issue. 
Were you able to retrieve this part from the beginning of the output?
````
BL=/home/user/aosp/treble_build_aosp
BD=/home/user/builds
```

**Comment by khaberz** [comment]
Here's the bginning of the output (after, again, the GUI):

`
+ case "$?" inment for Debian and Ubuntu Distros
+ [[ 1 6 =~ .*(1|2)+ ]]
+ [[ 1 6 != *\1\ \2* ]]
+ break
+ buildEnvCheck
+ [[ 1 6 == *\1* ]]
+ buildEnvDebian
+ sudo apt-get update
Hit:1 http://mirrors.linode.com/debian stable InRelease
Hit:2 http://mirrors.linode.com/debian stable-updates InRelease               
Hit:3 https://deb.debian.org/debian bookworm InRelease                        
Reading package lists... Done                           
+ sudo apt-get install -y git-core gnupg flex bc bison build-essential zip curl zlib1g-dev libc6-dev-i386 libncurses5 x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python3 clang repo git android-sdk-platform-tools-common openjdk-17-jdk
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'git' instead of 'git-core'
git is already the newest version (1:2.39.2-1.1).
gnupg is already the newest version (2.2.40-1.1).
bc is already the newest version (1.07.1-3+b1).
build-essential is already the newest version (12.9).
curl is already the newest version (7.88.1-10+deb12u4).
zlib1g-dev is already the newest version (1:1.2.13.dfsg-1).
zlib1g-dev set to manually installed.
libncurses5 is already the newest version (6.4-4).
unzip is already the newest version (6.0-28).
fontconfig is already the newest version (2.14.1-4).
fontconfig set to manually installed.
python3 is already the newest version (3.11.2-1+b1).
python3 set to manually installed.
The following additional packages will be installed:

`

**Comment by tabletseeker** [comment]
Yeah, the reason why you can't see that output might be due to dialog and a tty conflict with your term.

If you have the time, can you make this small modification in the code?

In build.sh add the following to line 82
```
echo "BL: $BL BD: $BD"
```
The function should look like this after:
```
buildEnvDebian() {

	sudo apt-get update && sudo apt-get install -y git-core gnupg flex bc bison \
	build-essential zip curl zlib1g-dev libc6-dev-i386 libncurses5 x11proto-core-dev \
	libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python3 \
	clang repo git android-sdk-platform-tools-common openjdk-17-jdk
	
	git config --global user.email "anon@ymous.com"
	git config --global user.name "johndoe"
	
	JAVA_DIR=$(ls /usr/lib/jvm | grep -Em1 java-[0-9]{2}-openjdk)
	export SKIP_ABI_CHECKS=true
	export JAVA_HOME=/usr/lib/jvm/$JAVA_DIR
        echo "BL: $BL BD: $BD"
}
```
That will tell us if $PWD is indeed empty at the beginning.

**Comment by khaberz** [comment]
Here you go:

`
+ case "$?" inment for Debian and Ubuntu Distros
+ [[ 1 6 =~ .*(1|2)+ ]]
+ [[ 1 6 != *\1\ \2* ]]
+ break
+ buildEnvCheck
+ [[ 1 6 == *\1* ]]
+ buildEnvDebian
+ sudo apt-get update
Hit:1 https://deb.debian.org/debian bookworm InRelease
Hit:2 http://mirrors.linode.com/debian stable InRelease
Hit:3 http://mirrors.linode.com/debian stable-updates InRelease
Reading package lists... Done
+ sudo apt-get install -y git-core gnupg flex bc bison build-essential zip curl zlib1g-dev libc6-dev-i386 libncurses5 x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python3 clang repo git android-sdk-platform-tools-common openjdk-17-jdk
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'git' instead of 'git-core'
git is already the newest version (1:2.39.2-1.1).
gnupg is already the newest version (2.2.40-1.1).
flex is already the newest version (2.6.4-8.2).
bc is already the newest version (1.07.1-3+b1).
bison is already the newest version (2:3.8.2+dfsg-1+b1).
build-essential is already the newest version (12.9).
zip is already the newest version (3.0-13).
curl is already the newest version (7.88.1-10+deb12u4).
zlib1g-dev is already the newest version (1:1.2.13.dfsg-1).
libc6-dev-i386 is already the newest version (2.36-9+deb12u3).
libncurses5 is already the newest version (6.4-4).
x11proto-core-dev is already the newest version (2022.1-1).
libx11-dev is already the newest version (2:1.8.4-2+deb12u2).
lib32z1-dev is already the newest version (1:1.2.13.dfsg-1).
libgl1-mesa-dev is already the newest version (22.3.6-1+deb12u1).
libxml2-utils is already the newest version (2.9.14+dfsg-1.3~deb12u1).
xsltproc is already the newest version (1.1.35-1).
unzip is already the newest version (6.0-28).
fontconfig is already the newest version (2.14.1-4).
python3 is already the newest version (3.11.2-1+b1).
clang is already the newest version (1:14.0-55.7~deb12u1).
repo is already the newest version (2.31-1).
android-sdk-platform-tools-common is already the newest version (28.0.2+9).
openjdk-17-jdk is already the newest version (17.0.9+9-1~deb12u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ git config --global user.email anon@ymous.com
+ git config --global user.name johndoe
++ ls /usr/lib/jvm
++ grep -Em1 'java-[0-9]{2}-openjdk'
+ JAVA_DIR=java-17-openjdk-amd64
+ export SKIP_ABI_CHECKS=true
+ SKIP_ABI_CHECKS=true
+ export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
+ JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
+ echo 'BL: /home/khaberz/aosp/treble_build_aosp BD: /home/khaberz/builds'
BL: /home/khaberz/aosp/treble_build_aosp BD: /home/khaberz/builds
`

**Comment by tabletseeker** [comment]
Ok good, that's fine then.
Must've been some weirdness before because of the sources.

Thank you for checking, I'll update the latest treble stuff and bump the new android version shortly.

If you're planning on completing the build, you'll need about 300GB of storage, min 16GB RAM (recommended 32GB) and about 20 - 30GB of SWAP space when your RAM gets saturated. Also, a CPU with min 4 Cores @4.5GHZ or it will take forever.
You could probably get away with a bit less storage because I use  `--depth=1` for repo init, which only pulls the latest stuff as opposed to everything.

If you can wait a bit, I'll have everything up and running soon.

**Comment by khaberz** [comment]
Thanks! My small VPS clearly is not the right environment then. I will find a spare SSD to make a Linux install here in the next couple days and try on that one.
I really do want to try this on my Tab S6 - Hardware is still top notch, a clean recent Android would be brilliant on it.

**Comment by tabletseeker** [comment]
If you really need something right now you can just install one of Ponce's AOSP releases. That will work fine with the Tab S6. https://github.com/ponces/treble_aosp/releases

That's the repo I forked, so it's basically identical, apart from the customization options.
