### ISSUE TITLE
Error online 57 immediately on running bash

### ISSUE THREAD

**Issue by Netradio-uk** [tabletseeker/treble_build_aosp#5]
## Info

```
Device: T860
GSI version: 
Vendor version: 
```

## Expected Behavior

```
Bash should run
```

## Current Behavior

```
Error on line 57
```

## Possible Solution

```
Assume may be Win11 running WSL
```

## Steps to Reproduce

```
1. Install WSL
2. sudo usermod -aG plugdev $LOGNAME
3. mkdir aosp; cd aosp
4. git clone https://github.com/tabletseeker/treble_build_aosp -b android-14.0
5. bash treble_build_aosp/build.sh
```

## Logs

AOSP 14.0 Buildbot\Zn \Z1by tablet_seeker\Zn"           --separator " "                 --item-help             --no-tags               --checklist "$(echo -e "\nPlease choose which stages you would like to customize during the build.\n\n Press \Zb\Zr Space \Zn to toggle an option on/off.\n\n           Press \Zb\Zr Arrow UP ↑ \Zn or \Zb\Zr Arrow DOWN ↓ \Zn to navitage options.\n\n         Press \Zb\Zr Arrow RIGHT → \Zn + \Zb\Zr Cancel \Zn to use default values.\n" | sed -e "s/\\t//g")" 16 61 0              "1" " Build Env Debian " "ON" "Build Environment for Debian and Ubuntu Distros"        "2" " Build Env Arch " "OFF"  "Build Environment for Arch Distros"               "3" " Custom System Settings " "OFF"  "Launch System Settings Form for Custom Value Selection"          "4" " Custom Android Version " "OFF" "Choose alternate Android Version"                 "5" " Custom File Selection " "OFF" "Choose individually which files are copied during build time"              "6" " Custom Signing Keys " "ON"  "Launch automatic creation of new signing keys"              "7" " Custom Patch Selection " "OFF"  "Individually choose which patches should be applied during build"
2>&1 1>&3`)
+++ echo -e '\nPlease choose which stages you would like to customize during the build.\n\n             Press \Zb\Zr Space \Zn to toggle an option on/off.\n\n          Press \Zb\Zr Arrow UP ↑ \Zn or \Zb\Zr Arrow DOWN ↓ \Zn to navitage options.\n\n         Press \Zb\Zr Arrow RIGHT → \Zn + \Zb\Zr Cancel \Zn to use default values.\n'
+++ sed -e 's/\t//g'
++ dialog --title '\ZbBuild Stage Selection\Zn' --colors --backtitle '\ZbAOSP 14.0 Buildbot\Zn \Z1by tablet_seeker\Zn' --separator ' ' --item-help --no-tags --checklist '
Please choose which stages you would like to customize during the build.

Press \Zb\Zr Space \Zn to toggle an option on/off.

Press \Zb\Zr Arrow UP ↑ \Zn or \Zb\Zr Arrow DOWN ↓ \Zn to navitage options.

Press \Zb\Zr Arrow RIGHT → \Zn + \Zb\Zr Cancel \Zn to use default values.' 16 61 0 1 ' Build Env Debian ' ON 'Build Environment for Debian and Ubuntu Distros' 2 ' Build Env Arch ' OFF 'Build Environment for Arch Distros' 3 ' Custom System Settings ' OFF 'Launch System Settings Form for Custom Value Selection' 4 ' Custom Android Version ' OFF 'Choose alternate Android Version' 5 ' Custom File Selection ' OFF 'Choose individually which files are copied during build time' 6 ' Custom Signing Keys ' ON 'Launch automatic creation of new signing keys' 7 ' Custom Patch Selection ' OFF 'Individually choose which patches should be applied during build'
+ case "$?" in
+ dialog --clear
treble_build_aosp/build.sh: line 57: dialog: command not found
+ true
+ exec
+ buildlist=(`dialog --title "\ZbBuild Stage Selection\Zn" "$@"                 --colors                --backtitle "\Zb

## Acknowledgements

- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] This issue is not related with kernel or Magisk at all.
- [X] I am not running a custom vendor on my device.
- [X] This issue occurs with the latest available build.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to this AOSP GSI.

**Comment by tabletseeker** [comment]
Hello, please make sure you installed the package dialog and included the correct sources if you're using Ubuntu or Debian. You can find the commands under dependencies on the [Readme Page](https://github.com/tabletseeker/treble_build_aosp#).
WSL should not be a problem, I would just recommend you use either Debian/Ubuntu or Arch because of their package repos.
